version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.6.1

jobs:
  minitest:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Run all Ruby files
          command: find . -name "*.rb" -print0 | xargs -0 -I@ sh -c 'ruby @'

workflows:
  continuous-integration:
    jobs:
      - minitest
