name: Ruby test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@4d521eadc80169779c35e0c9a59ee6c0f7dc18c2
        with:
          ruby-version: 2.6
      - name: Run tests
        run: find . -name "*.rb" -print0 | xargs -0 -I@ sh -c 'ruby @'
